version: "3.8"

services:
  database:
    image: mysql
    container_name: database_doctor_manager
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=doctor_manager
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: doctor_manager
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
